using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmAtlas.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddServicoTipoConfig : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotente de propósito: a tabela já foi criada por SQL bruto
            // (Program.cs) em bancos que rodaram a versão anterior do bootstrap.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS servico_tipo_config (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipo_servico character varying(32) NOT NULL,
                    nome character varying(80),
                    ordem integer NOT NULL DEFAULT 0,
                    ativo boolean NOT NULL DEFAULT true
                );

                CREATE UNIQUE INDEX IF NOT EXISTS uq_servico_tipo_config_tipo
                    ON servico_tipo_config (tipo_servico);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "servico_tipo_config");
        }
    }
}
