// <auto-generated />
using System;
using CrmAtlas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmAtlas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260723223716_InitialLegacySchema")]
    partial class InitialLegacySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AReceber")
                        .HasColumnType("numeric")
                        .HasColumnName("a_receber");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CondicaoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("condicao_pagamento");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Custos")
                        .HasColumnType("numeric")
                        .HasColumnName("custos");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("FolderUrl")
                        .HasColumnType("text")
                        .HasColumnName("folder_url");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<long>("OrigemId")
                        .HasColumnType("bigint")
                        .HasColumnName("origem_id");

                    b.Property<decimal?>("Recebido")
                        .HasColumnType("numeric")
                        .HasColumnName("recebido");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Subtipo")
                        .HasColumnType("text")
                        .HasColumnName("subtipo");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_servico");

                    b.Property<DateTime?>("UltimaMudancaSituacaoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_mudanca_situacao_em");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.HasKey("Id");

                    b.HasIndex("TipoServico", "OrigemId")
                        .IsUnique()
                        .HasDatabaseName("uk_acompanhamento_servico_origem");

                    b.ToTable("acompanhamento_servicos", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("NovaSituacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nova_situacao");

                    b.Property<long?>("ResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("ResponsavelNome")
                        .HasColumnType("text")
                        .HasColumnName("responsavel_nome");

                    b.Property<long>("ServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("servico_id");

                    b.Property<string>("SituacaoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("situacao_anterior");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.ToTable("acompanhamento_servico_historico", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoPendencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean")
                        .HasColumnName("concluida");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<long?>("PendenciaConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("pendencia_config_id");

                    b.Property<long>("ServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("servico_id");

                    b.Property<long?>("SituacaoConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("situacao_config_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PendenciaConfigId");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("idx_acompanhamento_pendencia_servico");

                    b.HasIndex("SituacaoConfigId")
                        .HasDatabaseName("idx_acompanhamento_pendencia_situacao");

                    b.ToTable("acompanhamento_servico_pendencias", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoSituacaoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool>("SituacaoInicial")
                        .HasColumnType("boolean")
                        .HasColumnName("situacao_inicial");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_servico");

                    b.HasKey("Id");

                    b.HasIndex("TipoServico", "Nome")
                        .IsUnique()
                        .HasDatabaseName("uk_acompanhamento_situacao_tipo_nome");

                    b.ToTable("acompanhamento_servico_situacao_config", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoSituacaoPendenciaConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<long>("SituacaoConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("situacao_config_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SituacaoConfigId", "Label")
                        .IsUnique()
                        .HasDatabaseName("uk_acompanhamento_pendencia_situacao_label");

                    b.ToTable("acompanhamento_situacao_pendencias", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Clientes.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj_cpf");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<string>("Rua")
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("CnpjCpf")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Documentos.PdfTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("uk_pdf_template_key");

                    b.ToTable("pdf_templates", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Financeiro.CustoIndireto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("custos_indiretos", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Financeiro.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CadastroServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cadastro_servico_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoServico")
                        .HasColumnType("text")
                        .HasColumnName("codigo_servico");

                    b.Property<string>("ComprovanteNomeArquivo")
                        .HasColumnType("text")
                        .HasColumnName("comprovante_nome_arquivo");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprovante_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateOnly?>("DataPrevistaParcela")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista_parcela");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pagamento");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NomePrestador")
                        .HasColumnType("text")
                        .HasColumnName("nome_prestador");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("origem");

                    b.Property<string>("Plataforma")
                        .HasColumnType("text")
                        .HasColumnName("plataforma");

                    b.Property<long?>("PrestadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("prestador_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CadastroServicoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PrestadorId");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Identidade.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth0Sub")
                        .HasColumnType("text")
                        .HasColumnName("auth0_sub");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text")
                        .HasColumnName("verification_code");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account_email");

                    b.Property<bool>("AutoSync")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_sync");

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EncryptedClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("integration_key");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("RedirectUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SyncIntervalMin")
                        .HasColumnType("integer")
                        .HasColumnName("sync_interval_min");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("webhook_enabled");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("google_integrations", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegrationAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("integration_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("google_integration_audit", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegrationScope", b =>
                {
                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("integration_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.HasKey("IntegrationId", "Scope");

                    b.ToTable("google_integration_scopes", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleSheetReportMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("integration_id");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("report_name");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("spreadsheet_id");

                    b.Property<string>("SpreadsheetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("spreadsheet_url");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("UpdatedRange")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("updated_range");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId", "ReportName")
                        .IsUnique()
                        .HasDatabaseName("uk_google_sheet_report_name_integration");

                    b.ToTable("google_sheet_report_metadata", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.WhatsAppMetaIntegration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessAccountId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EncryptedPermanentToken")
                        .HasColumnType("text")
                        .HasColumnName("permanent_token");

                    b.Property<string>("EncryptedWebhookVerifyToken")
                        .HasColumnType("text")
                        .HasColumnName("webhook_verify_token");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("integration_key");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumberId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("phone_number_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("webhook_enabled");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("whatsapp_meta_integrations", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.WhatsAppMetaIntegrationAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("integration_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("whatsapp_meta_integration_audit", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Notificacoes.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(38, 2)
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTimeOffset>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("ReferenceKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_key");

                    b.Property<string>("RuleType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rule_type");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Notificacoes.NotificationRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DaysThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("days_threshold");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("notification_rules", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.Avcb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AReceber")
                        .HasColumnType("numeric")
                        .HasColumnName("a_receber");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CondicaoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("condicao_pagamento");

                    b.Property<decimal?>("Custos")
                        .HasColumnType("numeric")
                        .HasColumnName("custos");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<string>("DescricaoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("descricao_situacao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nf")
                        .HasColumnType("text")
                        .HasColumnName("nf");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<decimal?>("Recebido")
                        .HasColumnType("numeric")
                        .HasColumnName("recebido");

                    b.Property<string>("Servico")
                        .HasColumnType("text")
                        .HasColumnName("servico");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("avcbs", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<long?>("CondicaoPagamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("condicao_pagamento_id");

                    b.Property<string>("ContatoEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("contato_empresa");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<DateOnly?>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("data_entrada");

                    b.Property<string>("DocumentoEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("documento_empresa");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EnderecoEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("endereco_empresa");

                    b.Property<string>("EnderecoServico")
                        .HasColumnType("text")
                        .HasColumnName("endereco_servico");

                    b.Property<bool>("MesmoEnderecoEmpresa")
                        .HasColumnType("boolean")
                        .HasColumnName("mesmo_endereco_empresa");

                    b.Property<string>("NomeCondicaoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("nome_condicao_pagamento");

                    b.Property<long?>("OrcamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("orcamento_id");

                    b.Property<string>("RazaoSocialEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("razao_social_empresa");

                    b.Property<string>("SituacaoInicial")
                        .HasColumnType("text")
                        .HasColumnName("situacao_inicial");

                    b.Property<string>("Subtipo")
                        .HasColumnType("text")
                        .HasColumnName("subtipo");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_servico");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.Property<decimal?>("ValorNotaFiscal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_nota_fiscal");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CondicaoPagamentoId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("cadastro_servicos", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServicoParcela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CadastroServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cadastro_servico_id");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CadastroServicoId");

                    b.ToTable("cadastro_servico_parcelas", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServicoPrestador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CadastroServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cadastro_servico_id");

                    b.Property<bool?>("Confirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmado");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("DataPagamentoTipo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("data_pagamento_tipo");

                    b.Property<string>("NomePrestador")
                        .HasColumnType("text")
                        .HasColumnName("nome_prestador");

                    b.Property<long?>("PrestadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("prestador_id");

                    b.Property<decimal?>("ValorEfetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_efetivo");

                    b.Property<decimal?>("ValorProvisionado")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_provisionado");

                    b.HasKey("Id");

                    b.HasIndex("CadastroServicoId");

                    b.HasIndex("PrestadorId");

                    b.ToTable("cadastro_servico_prestadores", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.Clcb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AReceber")
                        .HasColumnType("numeric")
                        .HasColumnName("a_receber");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<decimal?>("Custos")
                        .HasColumnType("numeric")
                        .HasColumnName("custos");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<string>("DescricaoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("descricao_situacao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nf")
                        .HasColumnType("text")
                        .HasColumnName("nf");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<decimal?>("Recebido")
                        .HasColumnType("numeric")
                        .HasColumnName("recebido");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("clcbs", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CondicaoPagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Indefinido")
                        .HasColumnType("boolean")
                        .HasColumnName("indefinido");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_dias");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("condicoes_pagamento", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.Obra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AReceber")
                        .HasColumnType("numeric")
                        .HasColumnName("a_receber");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CondicaoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("condicao_pagamento");

                    b.Property<decimal?>("Custos")
                        .HasColumnType("numeric")
                        .HasColumnName("custos");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<string>("DescricaoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("descricao_situacao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nf")
                        .HasColumnType("text")
                        .HasColumnName("nf");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<decimal?>("Recebido")
                        .HasColumnType("numeric")
                        .HasColumnName("recebido");

                    b.Property<string>("Servico")
                        .HasColumnType("text")
                        .HasColumnName("servico");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.Orcamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_servico");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.OrcamentoSituacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("orcamento_situacoes", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.Prestador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .HasColumnType("text")
                        .HasColumnName("agencia");

                    b.Property<string>("Banco")
                        .HasColumnType("text")
                        .HasColumnName("banco");

                    b.Property<string>("ChavePix")
                        .HasColumnType("text")
                        .HasColumnName("chave_pix");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_cpf");

                    b.Property<string>("Conta")
                        .HasColumnType("text")
                        .HasColumnName("conta");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pagamento");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("prestadores", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.ProcessoAdm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AReceber")
                        .HasColumnType("numeric")
                        .HasColumnName("a_receber");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CondicaoPagamento")
                        .HasColumnType("text")
                        .HasColumnName("condicao_pagamento");

                    b.Property<decimal?>("Custos")
                        .HasColumnType("numeric")
                        .HasColumnName("custos");

                    b.Property<DateOnly?>("DataContrato")
                        .HasColumnType("date")
                        .HasColumnName("data_contrato");

                    b.Property<string>("DescricaoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("descricao_situacao");

                    b.Property<string>("Nf")
                        .HasColumnType("text")
                        .HasColumnName("nf");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<DateOnly?>("ProximaParcela")
                        .HasColumnType("date")
                        .HasColumnName("proxima_parcela");

                    b.Property<decimal?>("Recebido")
                        .HasColumnType("numeric")
                        .HasColumnName("recebido");

                    b.Property<string>("Servico")
                        .HasColumnType("text")
                        .HasColumnName("servico");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<decimal?>("ValorContrato")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_contrato");

                    b.HasKey("Id");

                    b.ToTable("processos_adm", (string)null);
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoHistorico", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServico", "Servico")
                        .WithMany("Historicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoPendencia", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoSituacaoPendenciaConfig", "PendenciaConfig")
                        .WithMany()
                        .HasForeignKey("PendenciaConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServico", "Servico")
                        .WithMany("Pendencias")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoSituacaoConfig", "SituacaoConfig")
                        .WithMany()
                        .HasForeignKey("SituacaoConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PendenciaConfig");

                    b.Navigation("Servico");

                    b.Navigation("SituacaoConfig");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoSituacaoPendenciaConfig", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoSituacaoConfig", "SituacaoConfig")
                        .WithMany("Pendencias")
                        .HasForeignKey("SituacaoConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituacaoConfig");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Financeiro.Lancamento", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.CadastroServico", "CadastroServico")
                        .WithMany()
                        .HasForeignKey("CadastroServicoId");

                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId");

                    b.Navigation("CadastroServico");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegrationAudit", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegration", "Integration")
                        .WithMany("Audits")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegrationScope", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegration", "Integration")
                        .WithMany("Scopes")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleSheetReportMetadata", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegration", "Integration")
                        .WithMany("Reports")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.WhatsAppMetaIntegrationAudit", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Integracoes.WhatsAppMetaIntegration", "Integration")
                        .WithMany("Audits")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Notificacoes.Notification", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Identidade.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServico", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.CondicaoPagamento", "CondicaoPagamento")
                        .WithMany()
                        .HasForeignKey("CondicaoPagamentoId");

                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId");

                    b.Navigation("Cliente");

                    b.Navigation("CondicaoPagamento");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServicoParcela", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.CadastroServico", "CadastroServico")
                        .WithMany("Parcelas")
                        .HasForeignKey("CadastroServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadastroServico");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServicoPrestador", b =>
                {
                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.CadastroServico", "CadastroServico")
                        .WithMany("Prestadores")
                        .HasForeignKey("CadastroServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmAtlas.ApplicationCore.Servicos.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId");

                    b.Navigation("CadastroServico");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServico", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Pendencias");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Acompanhamentos.AcompanhamentoServicoSituacaoConfig", b =>
                {
                    b.Navigation("Pendencias");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.GoogleIntegration", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Reports");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Integracoes.WhatsAppMetaIntegration", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("CrmAtlas.ApplicationCore.Servicos.CadastroServico", b =>
                {
                    b.Navigation("Parcelas");

                    b.Navigation("Prestadores");
                });
#pragma warning restore 612, 618
        }
    }
}
