<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CrmAtlas.Web</RootNamespace>
    <AssemblyName>CrmAtlas.Frontend</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>crm-atlas-v2-auth0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.11.0" />
    <PackageReference Include="MudBlazor" Version="9.*" />
    <PackageReference Include="Radzen.Blazor" Version="11.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationCore\ApplicationCore.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
