<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CrmAtlas.Web</RootNamespace>
    <AssemblyName>CrmAtlas.Web</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>crm-atlas-v2-auth0</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.9.0" />
    <PackageReference Include="MudBlazor" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationCore\ApplicationCore.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>
</Project>
